apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-store
  namespace: default
spec:
  replicas: 1
  selector:
    matchLable: frontend
    aa: web
  template:
    metadata:
      name: online-store
      label:
        type: frontend
    spec:
      containers:
        - name: online-store-site
          image: getting-started
          
