apiVersion: v1
kind: Service
metadata:
  name: onlinestore-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    aa: web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
